### ISSUE TITLE
How to generate minidump of a process being debugged?

### ISSUE THREAD

**Issue by Evian-Zhang** [rust-minidump/minidump-writer#123]
There are situations where we want to use debuggers (such as gdb) to debug a certain process, and when a breakpoint is hitting, we want to generate a minidump of that process. However, if we call minidump_writer of a process that being debugged, an error of "No threads left to suspend out of 1" occurred. I wonder if it is technically possible to do such things?

**Comment by gabrielesvelto** [comment]
gdb has already ptrace()'d all the threads, so minidump_writer can't do it. It's theoretically possible to generate a minidump while skipping the thread suspension part (because you're guaranteeing that the threads are already suspended) but we don't have that in the current codebase. In the meantime you might want to generate core dumps directly from gdb if you want to do post-mortem debugging. Use `generate-core-file` in gdb for that.
