### ISSUE TITLE
[Request] Please add option to configure crash dump information type

### ISSUE THREAD

**Issue by italiks** [rust-minidump/minidump-writer#67]
Hi guys, thanks for your library!
I wanna ask to add an option to configure crash dump type like it suggested in the comment                 
```MiniDumpNormal,        // MINIDUMP_TYPE - we _might_ want to make this configurable```

Is it possible to configure Linux, MacOS dump type, or at least full dump?

**Comment by gabrielesvelto** [comment]
I'm not sure if I understand your request. This is the Windows minidump generation code, making it configurable would allow for the generation of full dumps for example - like the comment suggests - by passing `MiniDumpWithFullMemory` instead of `MiniDumpNormal`. That's definitely possible. What do you mean though with "Linux, macOS dump type"?
